#!/bin/bash
#WTM_AUTO_SWITCH helper script, written by papampi
#Feel free to use, change, edit and do what you want with it.

source /home/m1/1bash

BITCOIN="theGROUND"

# Creating a log file to record coin switch
LOG_FILE="/home/m1/8_wtmautoswitchlog"

if [ -e "$LOG_FILE" ] ; then
  #Limit the logfile, just keep the last 500K
 echo "$(cat $LOG_FILE | grep switched | tail -n 500k)" > $LOG_FILE
fi

while [ $BITCOIN == "theGROUND" ]
do

python2.7 '/home/m1/WTM_AUTO_SWITCH' /home/m1/WTM.json  | tee -a ${LOG_FILE}
sleep 5

CURRENT_COIN=$(head -n 150 /home/m1/1bash | grep COIN= | sed 's/COIN=//' | sed 's/\"//' | sed 's/\"//')
TOP_COIN=$(cat /home/m1/WTM_top_coin | grep : | sed 's/:[0-9][0-9]//' | sed 's/[0-9]//')
#TOP_COIN=$(cat /home/m1/top_coin)
TIMEIN=$WTM_AUTO_SWITCH_SYNC_INTERVAL
TIMEOUT=$(($TIMEIN * 60))
if [ "$CURRENT_COIN" != "$TOP_COIN" ]
then 
sed -i 's/'COIN=\"$CURRENT_COIN\"'/'COIN=\"$TOP_COIN\"/'' /home/m1/1bash
cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV 
sed -i '/^$/d' /home/m1/WTM_24H_REV
sleep 1


#kill last running wtm-miner
if ps aux | grep -v grep | grep -q wtm-miner
then
pkill -f wtm-miner
echo "wtm-miner Killed" | tee -a ${LOG_FILE}
fi
sleep 1

#MINER_PID=$(ps ax | grep SCREEN | grep miner)
#if [ -n  "$MINER_PID" ]
#then
#echo "miner is running, lets make the switch" | tee -a ${LOG_FILE}

#restart wdog
#kill $(ps aux | grep '[I]AmNotAJeep_and_Maxximus007_WATCHDOG' | awk '{print $2}')
pkill -f wdog
sleep 1
screen -dmS wdog bash /home/m1/IAmNotAJeep_and_Maxximus007_WATCHDOG
echo "$(date)  wdog restarted"

#kill miner
pkill -e miner
sleep 1
#start new wtm-miner
bash wtm-miner 

echo ""
echo "$(date) Mining switched from $CURRENT_COIN to $TOP_COIN" | tee -a ${LOG_FILE}
echo "Check again in $TIMEOUT seconds" #| tee -a ${LOG_FILE}
#else
#echo "miner not running, lets wait" | tee -a ${LOG_FILE}
#fi
sleep $TIMEOUT

else

echo ""
echo "$(date) Same Coin on Top, Continue mining $CURRENT_COIN"  # | tee -a ${LOG_FILE}
echo "Check again in $TIMEOUT seconds" #| tee -a ${LOG_FILE}
#kill last running wtm-miner
if ps aux | grep -v grep | grep -q wtm-miner
then
pkill -f wtm-miner
echo "wtm-miner Killed" | tee -a ${LOG_FILE}
fi
sleep 1

cat /home/m1/WTM_current_revenue | grep `cat /home/m1/WTM_top_coin | awk -F: '{print $1}'` | awk -F: '{print $2}' >> /home/m1/WTM_24H_REV
SYNC_COUNT=$((`expr 1440 / $WTM_AUTO_SWITCH_SYNC_INTERVAL`))
echo "$(tail -$SYNC_COUNT WTM_24H_REV)" > /home/m1/WTM_24H_REV 
sed -i '/^$/d' /home/m1/WTM_24H_REV

sleep $TIMEOUT
fi

done
